RSPayment/PaymentApp/Znode.Multifront.PaymentApplication/Znode.Multifront.PaymentApplication.Api/Controllers/ActivateController.cs
using System;
using System.Web.Mvc;
using Znode.Multifront.PaymentApplication.Helpers;
using Znode.Multifront.PaymentApplication.Models;

namespace Znode.Multifront.PaymentApplication.Api.Controllers
{
    public class ActivateController : Controller
    {
        public ActionResult Index() => View();

        public ActionResult LicenseInformation()
        {
            return View("LicenseInformation", new ActivateLicenceModel());
        }

        [HttpPost]
        public ActionResult Create(ActivateLicenceModel model)
        {
            if (!Equals(model.LicenseType, "FreeTrial") && string.IsNullOrEmpty(model.SerialNumber))
            {
                ModelState.AddModelError("SerialNumber", "Serial number is required");
            }

            if (ModelState.IsValid)
            {
                string message = String.Empty;
                LicenceHelper _service = new LicenceHelper();
                if (_service.InstallLicense(model.LicenseType, model.SerialNumber, model.FullName, model.Email, out message))
                {
                    // Confirmation page 
                    model.Message = "Your Znode license has been successfully activated.";
                }
                else
                {
                    model.ErrorMessage = "Failed to activate license. Additional info: " + message;
                }
            }
            return View("LicenseInformation", model);
        }

        /// <summary>
        /// Update License
        /// </summary>
        /// <returns></returns>
        public ActionResult UpdateLicense()
        {
            string message = String.Empty;
            LicenceHelper _service = new LicenceHelper();         

            return (_service.UpdateLicense(out message))
                ? Content("Your Znode license has been updated successfully. ")
                : Content(message);
        }
    }
}

RSPayment/PaymentApp/Znode.Multifront.PaymentApplication/Znode.Multifront.PaymentApplication.Api/Views/Activate/Index.cshtml
@{
    ViewBag.Title = "Znode Activation";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-3.3.1.min.js")" type="text/javascript"></script>
<script type="text/javascript">
	$(document).ready(function () {
	    $("#Checkbox1").click(function () {
			$('#ActivateButton').attr("disabled", !this.checked);
		});

		$("input[name$='LicenseType']").click(function () {
			var value = $(this).val();
			if (value == 'FreeTrial') {
				$("#serialNumberRow").hide();
			} else {
				$("#serialNumberRow").show();
			}
		});
	});
</script>

@using (Html.BeginForm("LicenseInformation", "Activate"))
{
    <div id="body">
        <h2>Activate your License</h2>

        <section id="Display">
            <p>
                You are about to activate your license.<br>
                If you are activating a Free Trial then proceed with the activation. You will have the option of creating an activation without using a license key.
                <br />
                If you are using a purchased license, then you should be aware that this activation can only be used on one CPU.
                <br />
                <br />
                @Html.ActionLink("Click here", "Updatelicense", "Activate", null, null) to check for update of your existing license.
                <br />
            </p>

            <input id="Checkbox1" type="checkbox" /> Yes I wish to activate my license for this CPU. I also understand that once activated, my key can only be used on this CPU.<br>

            <br />

            <input id="ActivateButton" type="submit" value="Proceed With Activation" disabled="disabled" />
        </section>
    </div>
}

RSPayment/PaymentApp/Znode.Multifront.PaymentApplication/Znode.Multifront.PaymentApplication.Api/Views/Activate/LicenseInformation.cshtml
@{
    ViewBag.Title = "Znode Activation";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Znode.Multifront.PaymentApplication.Models.ActivateLicenceModel

<section id="Display">
    @using (Html.BeginForm("Create", "Activate", FormMethod.Post))
    {
        <div id="body">
            <h2>Activate your License</h2>
            <b>Please Note:</b>
            <ul>
                <li>You are activating your license to this server. Be sure this is what you want to do!</li>
                <li>Once your key is registered you will not be able to change the URL.</li>
                <li>Choosing the 30 Day Free Trial will not count toward your license activation.</li>
                <li>You must have Read+Write+Modify permissions for the Network Service account on the folder before activating.</li>
            </ul>

            <table style="width: 100%; border: 1px" border="1">
                <tr>
                    <td width="30%"><b>Select License</b></td>
                    <td></td>
                </tr>
                @if (!string.IsNullOrEmpty(Model.Message))
                {
                    <tr>
                        <td width="30%" style="color: green; font: bold" colspan="2">@Model.Message @Html.ActionLink("Click Here", "Index", "Home", new { area = "" }, null) to redirect to Homepage.</td>
                    </tr>
                }
                <tr>
                    <td width="30%" style="color: red; font: bold" colspan="2">@Model.ErrorMessage</td>
                </tr>
                <tr>
                    <td></td>
                    <td>@Html.RadioButtonFor(m => m.LicenseType, "API", new { @class = "radio-btn" })<label>API</label></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>@Html.RadioButtonFor(m => m.LicenseType, "FreeTrial", new { @class="radio-btn" })<label>30 Day Free Trial</label></td>
                </tr>
            </table>

            <table style="width: 100%;">
                <tr id="serialNumberRow" style="display: none;">
                    <td width="30%"><b>Serial Number</b></td>
                    <td>
                        @Html.TextBoxFor(m => m.SerialNumber)
                        @Html.ValidationMessageFor(m => m.SerialNumber)
                    </td>
                </tr>
                <tr>
                    <td width="30%"><b>Full Name</b></td>
                    <td>
                        @Html.TextBoxFor(m => m.FullName)
                        @Html.ValidationMessageFor(m => m.FullName)
                    </td>
                </tr>
                <tr>
                    <td><b>Email Address</b></td>
                    <td>
                        @Html.TextBoxFor(m => m.Email)
                        @Html.ValidationMessageFor(m => m.Email)
                    </td>
                </tr>
            </table>

            @Html.TextAreaFor(m => m.Eula, new { cols = "100", rows = "30" })
            <br />

            @Html.CheckBoxFor(m => m.CheckEula)
            <label>I have read and agreed to the software license agreement (EULA) above</label>
            @Html.ValidationMessageFor(m => m.CheckEula)
            <br />

            <input id="ActivateLicense" type="submit" value="Click to Activate License" />
        </div>
    }
</section>

<script type="text/javascript">
    $(document).ready(function () {
        showSerialNumber();

        $('input:radio').change(function () {
            var value = $(this).val();
            if (value == 'FreeTrial') {
                $("#serialNumberRow").hide();
            } else {
                $("#serialNumberRow").show();
            }
        });

        function showSerialNumber() {
            var selected = $("input[type='radio'][name='LicenseType']:checked");

            if (selected.length > 0) {
                var selectedValue = selected.val();
                if (selectedValue == 'FreeTrial') {
                    $("#serialNumberRow").hide();
                } else {
                    $("#serialNumberRow").show();
                }
            }
        }
    });
</script>